name: bc_ur_dart
description: A dart plugin for Uniform Resources(URs) decode/encode. URs are URI-encoded CBOR structures developed by Blockchain Commons.
version: 0.1.0
repository: https://github.com/fxwalletOfficial/bc_ur_dart

environment:
  sdk: ^3.3.4

dependencies:
  cbor: ^6.3.3
  convert: ^3.1.1
  crypto: ^3.0.3
  xrandom: ^0.7.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
